export const clientsContext = {
    items: [
        {
            name: 'Северсталь',
            href: '#',
            ariaLabel: 'Перейти на сайт Северсталь',
            logo: '/images/clients/severstal-logo.svg',
            modifier: 'severstal',
        },
        {
            name: 'SIBUR',
            href: '#',
            ariaLabel: 'Перейти на сайт SIBUR',
            logo: '/images/clients/sibur-logo.svg',
            modifier: 'sibur',
        },
        {
            name: 'ТЭК-Торг',
            href: '#',
            ariaLabel: 'Перейти на сайт ТЭК-Торг',
            logo: '/images/clients/tek-logo.svg',
            modifier: 'tek',
        },
        {
            name: 'ROSATOM',
            href: '#',
            ariaLabel: 'Перейти на сайт ROSATOM',
            logo: '/images/clients/rosatom-logo.svg',
            modifier: 'rosatom',
        },
        {
            name: 'НЛМК',
            href: '#',
            ariaLabel: 'Перейти на сайт НЛМК',
            logo: '/images/clients/hlmk-logo.svg',
            modifier: 'hlmk',
        },
        {
            name: 'Ростех',
            href: '#',
            ariaLabel: 'Перейти на сайт Ростех',
            logo: '/images/clients/rosteh-logo.svg',
            modifier: 'rosteh',
        },
        {
            name: 'УРАЛХИМ',
            href: '#',
            ariaLabel: 'Перейти на сайт УРАЛХИМ',
            logo: '/images/clients/uralchem-logo.svg',
            modifier: 'uralchem',
        },
        {
            name: 'Schlumberger',
            href: '#',
            ariaLabel: 'Перейти на сайт Schlumberger',
            logo: '/images/clients/schlumberger-logo.svg',
            modifier: 'schlumberger',
        },
        {
            name: 'MR GROUP',
            href: '#',
            ariaLabel: 'Перейти на сайт MR GROUP',
            logo: '/images/clients/mr-logo.svg',
            modifier: 'mr',
        },
        {
            name: 'COLDY',
            href: '#',
            ariaLabel: 'Перейти на сайт COLDY',
            logo: '/images/clients/coldy-logo.svg',
            modifier: 'coldy',
        },
        {
            name: 'ГЛАВСТРОЙ',
            href: '#',
            ariaLabel: 'Перейти на сайт ГЛАВСТРОЙ',
            logo: '/images/clients/glavstroy-logo.svg',
            modifier: 'glavstroy',
        },
        {
            name: 'VK',
            href: '#',
            ariaLabel: 'Перейти на сайт VK',
            logo: '/images/clients/vk-logo.svg',
            modifier: 'vk',
        },
        {
            name: 'открытие',
            href: '#',
            ariaLabel: 'Перейти на сайт открытие',
            logo: '/images/clients/open-logo.svg',
            modifier: 'open',
        },
        {
            name: 'СБЕР',
            href: '#',
            ariaLabel: 'Перейти на сайт СБЕР',
            logo: '/images/clients/sber-logo.svg',
            modifier: 'sber',
        },
        {
            name: 'Фармстандарт',
            href: '#',
            ariaLabel: 'Перейти на сайт Фармстандарт',
            logo: '/images/clients/phs-logo.svg',
            modifier: 'phs',
        },
    ],
}
