export const portfolioContext = {
    label: 'проекты',
    description:
        'Обеспечиваем компании лучшими техническими и дизайн-решениями, <br> создавая digital-проекты.',
    mobileDescription: 'Only — digital–агентство с фокусом на сильную аналитику, дизайн и разработку. В основе наших проектов лежат идеи, создаваемые на стыке стратегии, креатива и технологий.',
    categories: [
        {
            title: 'Крупнейшие компании',
            items: [
                {
                    id: 'sibur',
                    title: 'Сибур',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/sibur-smaller.webp',
                        'webp@2x': '/images/portfolio/sibur-smaller@2x.webp',
                        'jpeg': '/images/portfolio/sibur-smaller.png',
                        'jpeg@2x': '/images/portfolio/sibur-smaller@2x.png',
                    },
                },
                {
                    id: 'mr-group',
                    title: 'MR group',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/mr.webp',
                        'webp@2x': '/images/portfolio/mr@2x.webp',
                        'png': '/images/portfolio/mr.png',
                        'png@2x': '/images/portfolio/mr@2x.png',
                    },
                },
                {
                    id: 'severstal',
                    title: 'Северсталь',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/severstal.webp',
                        'webp@2x': '/images/portfolio/severstal@2x.webp',
                        'png': '/images/portfolio/severstal.png',
                        'png@2x': '/images/portfolio/severstal@2x.png',
                    },
                },
            ],
        },
        {
            title: 'Девелоперы',
            items: [
                {
                    id: 'whoosh',
                    title: 'WHOOSH',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/whoosh.webp',
                        'webp@2x': '/images/portfolio/whoosh@2x.webp',
                        'jpeg': '/images/portfolio/whoosh.png',
                        'jpeg@2x': '/images/portfolio/whoosh@2x.png',
                    },
                },
                {
                    id: 'rsd',
                    title: 'Сайт R&D-центра НЛМК',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/rd.webp',
                        'webp@2x': '/images/portfolio/rd@2x.webp',
                        'jpeg': '/images/portfolio/rd.png',
                        'jpeg@2x': '/images/portfolio/rd@2x.png',
                    },
                },
                {
                    id: 'academy',
                    title: 'Новые академики',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/new-academy.webp',
                        'webp@2x': '/images/portfolio/new-academy@2x.webp',
                        'jpeg': '/images/portfolio/new-academy.png',
                        'jpeg@2x': '/images/portfolio/new-academy@2x.png',
                    },
                },
            ],
        },
        {
            title: 'B2C',
            items: [
                {
                    id: 'water',
                    title: 'Аш-Тау',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/ash-tau.webp',
                        'webp@2x': '/images/portfolio/ash-tau@2x.webp',
                        'jpeg': '/images/portfolio/ash-tau.png',
                        'jpeg@2x': '/images/portfolio/ash-tau@2x.png',
                    },
                },
                {
                    id: 'wheat',
                    title: 'Уралхим',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/ural-chem.webp',
                        'webp@2x': '/images/portfolio/ural-chem@2x.webp',
                        'jpeg': '/images/portfolio/ural-chem.png',
                        'jpeg@2x': '/images/portfolio/ural-chem@2x.png',
                    },
                },
                {
                    id: 'circles',
                    title: 'Плати частями',
                    meta: '3D, Анимация, Production, Web-design',
                    href: '#',
                    image: {
                        'webp': '/images/portfolio/pay-partly.webp',
                        'webp@2x': '/images/portfolio/pay-partly@2x.webp',
                        'jpeg': '/images/portfolio/pay-partly.png',
                        'jpeg@2x': '/images/portfolio/pay-partly@2x.png',
                    },
                },
            ],
        },
    ],
    desktopItems: [
        {
            id: 'sibur',
            title: 'Корпоративный сайт Сибура',
            meta: 'Адаптация нового брендинга для digital. Разработка, дизайн <br> основного сайта и подразделений',
            href: '#',
            image: {
                'webp': '/images/portfolio/sibur.webp',
                'webp@2x': '/images/portfolio/sibur@2x.webp',
                'png': '/images/portfolio/sibur.png',
                'png@2x': '/images/portfolio/sibur@2x.png',
            },
        },
        {
            id: 'severstal',
            title: 'Корпоративный сайт Северстали',
            meta: 'Единая digital-платформа, объединяющая группу сайтов и суббрендов компании. Блочная разработка, формирование дизайн-системы и цифрового брендбука',
            href: '#',
            image: {
                'webp': '/images/portfolio/severstal.webp',
                'webp@2x': '/images/portfolio/severstal@2x.webp',
                'png': '/images/portfolio/severstal.png',
                'png@2x': '/images/portfolio/severstal@2x.png',
            },
        },
        {
            id: 'vk-capsule',
            title: 'Лендинг VK Капсула Про',
            meta: 'Дизайн промо-лендинга для флагманской колонки VK',
            href: '#',
            image: {
                'webp': '/images/portfolio/vk.webp',
                'webp@2x': '/images/portfolio/vk@2x.webp',
                'png': '/images/portfolio/vk.png',
                'png@2x': '/images/portfolio/vk@2x.png',
            },
        },
        {
            id: 'mr-group',
            title: 'Маркетплейс недвижимости MR Group',
            meta: 'UX-проектирование и дизайн интерфейса, который увеличил конверсию бронирования квартир',
            href: '#',
            image: {
                'webp': '/images/portfolio/mr-nature.webp',
                'webp@2x': '/images/portfolio/mr-nature@2x.webp',
                'png': '/images/portfolio/mr-nature.png',
                'png@2x': '/images/portfolio/mr-nature@2x.png',
            },
        },
        {
            id: 'academy',
            title: 'Сайт ЖК Новые академики',
            meta: 'UX-проектирование, UI/UX-дизайн, разработка на Next.js сайта ЖК Главстроя',
            href: '#',
            image: {
                'webp': '/images/portfolio/new-academy-flowers.webp',
                'webp@2x': '/images/portfolio/new-academy-flowers@2x.webp',
                'jpeg': '/images/portfolio/new-academy-flowers.png',
                'jpeg@2x': '/images/portfolio/new-academy-flowers@2x.png',
            },
        },
        {
            id: 'ash-tau',
            title: 'Промосайт Аш-тау',
            meta: 'Промосайт, 3D-визуализация и карта глубин для бренда минеральной воды',
            href: '#',
            image: {
                'webp': '/images/portfolio/ash-tau.webp',
                'webp@2x': '/images/portfolio/ash-tau@2x.webp',
                'png': '/images/portfolio/ash-tau.png',
                'png@2x': '/images/portfolio/ash-tau@2x.png',
            },
        },
        {
            id: 'rd',
            title: 'Сайт RGD-центра НЛМК',
            meta: 'Креативная концепция, разработка сайта и дизайн для направления R&D НЛМК',
            href: '#',
            image: {
                'webp': '/images/portfolio/rd.webp',
                'webp@2x': '/images/portfolio/rd@2x.webp',
                'png': '/images/portfolio/rd.png',
                'png@2x': '/images/portfolio/rd@2x.png',
            },
        },
        {
            id: 'stool',
            title: 'Интернет-магазин Stool Group',
            meta: 'Онлайн-магазин с акцентом на заботу и комфорт. Создание бренд-платформы и digital-айдентики, разработка сервисных UX-решений',
            href: '#',
            image: {
                'webp': '/images/portfolio/stool.webp',
                'webp@2x': '/images/portfolio/stool@2x.webp',
                'png': '/images/portfolio/stool.png',
                'png@2x': '/images/portfolio/stool@2x.png',
            },
        },
        {
            id: 'ural-chem',
            title: 'Сайт агропродукции Уралхим',
            meta: 'Продуктовый сайт, каталог продукции, семантическое проектирование',
            href: '#',
            image: {
                'webp': '/images/portfolio/ural-chem.webp',
                'webp@2x': '/images/portfolio/ural-chem@2x.webp',
                'png': '/images/portfolio/ural-chem.png',
                'png@2x': '/images/portfolio/ural-chem@2x.png',
            },
        },
    ],
    button: {
        text: 'все проекты',
        href: '#',
    },
}
